spring.application.name=earthquake-app

# DB location / info
spring.datasource.url=jdbc:postgresql://localhost:5432/earthquakedb
spring.datasource.username=earthquake_user
spring.datasource.password=earthquake

# auto create tables from java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# app runs on port:
server.port=8080

# USGS API link
app.usgs.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
app.filter.min-magnitude=2.0
